#: import menu menu
MainWidget:


<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: "image/250537.jpg"
    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height * 0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_value
        font_name: 'fonts/Lcd.ttf'
        font_size: self.width/8
        size_hint: 0.2, 0.2
        pos_hint: {'x': 0, 'top': 1}